### ISSUE TITLE
SQReen with babel

### ISSUE THREAD

**Issue by victorlucss** [sqreen/sqreen-demo-app#6]
Hello! First of all, I'd have to say thank you for ur support of Node and everything you're doing to improve our experience as developers. 

I've found one error when using Sqreen with Babel and may you can answer why this occurs and how to solve that problem. 

When I import the Sqreen in my main file (in my case, `index.js`) the following message is shown on my terminal: 

```
It seems that the following modules have been required before Sqreen:
- /my/application/path/node_modules/commander/index.js
- /my/application/path/node_modules/@babel/core/lib/index.js
- /my/application/path/node_modules/core-js/stable/index.js
- /my/application/path/node_modules/regenerator-runtime/runtime.js
- /my/application/path/node_modules/@babel/register/lib/index.js
- /my/application/path/node_modules/resolve/index.js
- /my/application/path/node_modules/@babel/node/package.json
Sqreen may not be able to protect the whole application.
If you think this is an error, please report it to Sqreen team.
Read more on https://doc.sqreen.io/docs/nodejs-agent-installation
```

I've changed the order of imports but none of my modifications can solve this problem/warn. My `index.js` file: 

```javascript
import 'sqreen'
import app from './app'
import environment from '../../config/environment'

app.listen(environment.appPort)
console.log(`[SERVER] Started ${environment.nodeEnv} in port ${environment.appPort}`)
```

I've not found some article or issue relating this trouble on google (searching for "sqreen babel warning")

Is there a way to solve this?

Thansk a lot!

**Comment by vdeturckheim** [comment]
Hey @victorlucss ,

I am terribly sorry for this very late reply: this repository is not the right one for posting issues regarding Sqreen for Node.js: it contains a demo app. Issues regarding the agent should be sent the support email address.

To give you a quick answer on this, please try to start the process with `node -r sqreen index,js`, this will force Sqreen to be loaded first. Let me know if that works.
Cheers,
Vlad

**Comment by vdeturckheim** [comment]
Closing as not related to the repo, feel free to contact us here or somewhere else :)
